### ISSUE TITLE
Text corrupts itself while making a map

### ISSUE THREAD

**Issue by Kaylerr** [thelightdesigner/ScuffedWalls#26]
Whenever i use the function 'TextToWall' i often get this mess in my game: 
![image](https://user-images.githubusercontent.com/71836631/153045360-231bf76c-3c03-429d-90a6-138d664db557.png).
(the sentence is mean't to be: 'Stronger by Jess and Leigh')

After that, i tried again with a different word, however i got this: 
![image](https://user-images.githubusercontent.com/71836631/153045443-41b53f98-2c50-49a8-8ad7-c0d38feda7d8.png)
(the word is mean't to be 'Try')

My code is as accordingly:
```
0:TextToWall
definitedurationbeats:16
path:acloudyskye_font.dae
line: Try
thicc:12
size:0.7
animatedefiniteposition:[0, 1, 0, 0]
```

Why do i get this error when my code seems correct? Please help me out here. Thanks in advance - Kaylerr, "Noodle is stupidly cool" (2022)

**Comment by Reddek2000** [comment]
I think you have bloom turned off. Either turn it back on in settings or download this mods to fix it:
https://github.com/kinsi55/BeatSaber_Tweaks55/releases
(Enable "Disable 'fake wall bloom") in the mods settings

**Comment by thelightdesigner** [comment]
Yeah that looks like bloom is off.

**Comment by Kaylerr** [comment]
😿 why would the walls kill itself over this?!

anyway, done. It works now. :)
